name: 'Installs vessel'
description: 'Installs vessel'
inputs:
  vessel_version:
    description: 'Vessel version to install'
    default: '0.6.0'
runs:
  using: "composite"
  steps:
    - name: "create bin directory"
      shell: bash
      run: |
       mkdir -p /home/runner/bin
       echo "$HOME/bin" >> $GITHUB_PATH
    - name: "install vessel"
      shell: bash
      run: |
       wget --output-document $HOME/bin/vessel https://github.com/kritzcreek/vessel/releases/download/v${{inputs.vessel_version}}/vessel-linux64
       chmod +x /home/runner/bin/vessel
